"""empty message

Revision ID: 1ae4039ae567
Revises: None
Create Date: 2014-11-06 16:06:03.103976

"""

# revision identifiers, used by Alembic.
revision = '1ae4039ae567'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('case', sa.Text(), nullable=True),
    sa.Column('mhd', sa.Text(), nullable=True),
    sa.Column('cda', sa.Text(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    ### end Alembic commands ###
