"""empty message

Revision ID: 2fe22d2c0b14
Revises: 3693e9c1ccf3
Create Date: 2014-11-07 14:10:46.489242

"""

# revision identifiers, used by Alembic.
revision = '2fe22d2c0b14'
down_revision = '3693e9c1ccf3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'name')
    ### end Alembic commands ###
