"""empty message

Revision ID: 540dcd2e46ff
Revises: 5ae36d46c558
Create Date: 2014-11-06 15:24:53.766087

"""

# revision identifiers, used by Alembic.
revision = '540dcd2e46ff'
down_revision = '5ae36d46c558'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('case', sa.Text(), nullable=True),
    sa.Column('mdh', sa.Text(), nullable=True),
    sa.Column('cda', sa.Text(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_text', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default="nextval('users_id_seq'::regclass)", nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'users_pkey')
    )
    op.drop_table('records')
    ### end Alembic commands ###
